/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.retaurant.GUI.DatBan;

/**
 *
 * @author light
 */
public class ActionTableCellPanel extends javax.swing.JPanel {

    /**
     * Creates new form BtnCellTablePn
     */
    public ActionTableCellPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOder = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        btnOder.setText("Đặt bàn");
        btnOder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOderActionPerformed(evt);
            }
        });
        add(btnOder);

        btnDetail.setText("Chi tiết");
        add(btnDetail);

        btnCancel.setText("Hủy");
        btnCancel.setDisplayedMnemonicIndex(0);
        add(btnCancel);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnOder;
    // End of variables declaration//GEN-END:variables
}
