/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.retaurant.GUI.CongThuc;

import com.example.retaurant.BUS.CongThucBUS;
import com.example.retaurant.BUS.MonAnBUS;
import com.example.retaurant.BUS.NguyenLieuBUS;
import com.example.retaurant.DTO.CongThucDTO;
import com.example.retaurant.DTO.MonAnDTO;
import com.example.retaurant.DTO.NguyenLieuDTO;
import java.sql.SQLException;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class CongThucPannel extends javax.swing.JPanel {

    /**
     * Creates new form CongThucPannel
     */
    public CongThucPannel() {
        initComponents();
        loadCongThuc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1108, 524));

        jButton4.setText("Thêm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Món Ăn", "Tên Món Ăn", "Giá"
            }
        ));
        jTable1.setMaximumSize(new java.awt.Dimension(2147483647, 280));
        jTable1.setPreferredSize(new java.awt.Dimension(500, 412));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Nguyên Liệu ", "Tên Nguyên Liệu", "Số lượng (g)"
            }
        ));
        jTable3.setMaximumSize(new java.awt.Dimension(2147483647, 12312380));
        jTable3.setPreferredSize(new java.awt.Dimension(500, 80));
        jScrollPane3.setViewportView(jTable3);

        jLabel1.setText("Tìm theo tên món ăn");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xoá");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int rowMonAn = jTable1.getSelectedRow();

        if (rowMonAn == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn món ăn để sửa.");
            return;
        }
        
        String tenMonAn = jTable1.getValueAt(rowMonAn, 1).toString();
        String idMonAn = jTable1.getValueAt(rowMonAn, 0).toString();

        AddCongThuc fthem = new AddCongThuc(idMonAn,tenMonAn);
        fthem.setVisible(true);
        
        fthem.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            try {
                loadNguyenLieuTheoMon(idMonAn);
            } catch (SQLException ex) {
                Logger.getLogger(CongThucPannel.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        });
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            String idMonAn = jTable1.getValueAt(row, 0).toString();
            try {
                loadNguyenLieuTheoMon(idMonAn);
            } catch (SQLException ex) {
                Logger.getLogger(CongThucPannel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String[] columnNames = {"ID món ăn", "Tên món ăn", "Giá"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
        jTable1.setModel(tableModel);
        tableModel.setRowCount(0);
        MonAnBUS monAnBUS = new MonAnBUS();
        List<MonAnDTO> dsMonAn = monAnBUS.searchMonAnByName(jTextField1.getText());
        for (MonAnDTO monAn : dsMonAn) {
            tableModel.addRow(new Object[]{monAn.getSpId(), monAn.getTenSp(), monAn.getGiaSp()});
            
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int rowMonAn = jTable1.getSelectedRow();
        int rowNguyenLieu = jTable3.getSelectedRow();

        if (rowMonAn == -1 || rowNguyenLieu == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn món ăn và nguyên liệu để sửa.");
            return;
        }

        // Lấy thông tin món ăn và nguyên liệu
        String tenMonAn = jTable1.getValueAt(rowMonAn, 1).toString();
        String tenNguyenLieu = jTable3.getValueAt(rowNguyenLieu, 1).toString();
        String soLuongCu = jTable3.getValueAt(rowNguyenLieu, 2).toString();
        String idMonAn = jTable1.getValueAt(rowMonAn, 0).toString();
        String idNguyenLieu = jTable3.getValueAt(rowNguyenLieu, 0).toString();

        // Hiển thị hộp thoại để người dùng nhập số lượng mới
        String input = JOptionPane.showInputDialog(null,
            "Tên món ăn: " + tenMonAn + "\n" +
            "Nguyên liệu: " + tenNguyenLieu + "\n" +
            "Số lượng cũ: " + soLuongCu + " g\n" +
            "Nhập số lượng mới (g):",
            soLuongCu);

        if (input == null || input.trim().isEmpty()) return;

        try {
            int soLuongMoi = Integer.parseInt(input.trim());

            if (soLuongMoi <= 0) {
                JOptionPane.showMessageDialog(null, "Số lượng phải lớn hơn 0.");
                return;
            }

            // Cập nhật số lượng mới vào cơ sở dữ liệu
            CongThucBUS ctBUS = new CongThucBUS();
            CongThucDTO ct = new CongThucDTO(Integer.parseInt(idMonAn), Integer.parseInt(idNguyenLieu), soLuongMoi);
            boolean isUpdated = ctBUS.updateCongThuc(ct);

            if (isUpdated) {
                JOptionPane.showMessageDialog(null, "Cập nhật công thức thành công!");
                loadNguyenLieuTheoMon(idMonAn); // Load lại bảng nguyên liệu sau khi sửa
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật công thức không thành công. Vui lòng thử lại.");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Số lượng không hợp lệ!");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi sửa công thức: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void loadCongThuc(){
        String[] columnNames = {"ID món ăn", "Tên món ăn", "Giá"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
        jTable1.setModel(tableModel);
        tableModel.setRowCount(0);
        MonAnBUS monAnBUS = new MonAnBUS();
        List<MonAnDTO> dsMonAn = monAnBUS.getAllMonAn();
        for (MonAnDTO monAn : dsMonAn) {
            tableModel.addRow(new Object[]{monAn.getSpId(), monAn.getTenSp(), monAn.getGiaSp()});
            
        }
        jTable1.setDefaultEditor(Object.class, null);
        jTable3.setDefaultEditor(Object.class, null);
    }
    private void loadNguyenLieuTheoMon(String idMonAn) throws SQLException {
        String[] Names = {"ID Nguyên Liệu", "Tên Nguyên Liêu", "Số Lượng (g)"};
        DefaultTableModel model = new DefaultTableModel(Names, 0);
        jTable3.setModel(model);
        model.setRowCount(0);

        CongThucBUS congThucBUS = new CongThucBUS();
        List<CongThucDTO> dsct= congThucBUS.getAllCongThuc();

        NguyenLieuBUS nguyenLieuBUS = new NguyenLieuBUS();
        List<NguyenLieuDTO> dsnl =nguyenLieuBUS.getAllNguyenLieu();

        for(CongThucDTO ct : dsct){
            if(Objects.equals(ct.getSpid(), Integer.valueOf(idMonAn))){
                String idNL = null;
                String tenNL = null;
                for (NguyenLieuDTO nl : dsnl) {
                    if(Objects.equals(ct.getNlid(), nl.getNlId())){
                        idNL = nl.getNlId().toString();
                        tenNL = nl.getTenNl();
                        break;
                    }
                }
                String sol = Float.toString(ct.getSoluong());
                model.addRow(new Object[]{idNL,tenNL, sol});
                model.fireTableDataChanged();
            }
            
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int rowMonAn = jTable1.getSelectedRow();
        int rowNguyenLieu = jTable3.getSelectedRow();

        if (rowMonAn == -1 || rowNguyenLieu == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn món ăn và nguyên liệu để xoá.");
            return;
        }

        String idMonAn = jTable1.getValueAt(rowMonAn, 0).toString();
        String idNguyenLieu = jTable3.getValueAt(rowNguyenLieu, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(null,
            "Bạn có chắc muốn xoá công thức của món này?",
            "Xác nhận xoá",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                CongThucBUS ctBUS = new CongThucBUS();
                ctBUS.deleteCongThuc(Integer.parseInt(idMonAn), Integer.parseInt(idNguyenLieu));
                JOptionPane.showMessageDialog(null, "Xoá công thức thành công!");

                // Cập nhật lại bảng nguyên liệu bên phải
                loadNguyenLieuTheoMon(idMonAn);

            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Lỗi khi xoá công thức: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
            JFrame frame = new JFrame("Quản Lý Món Ăn");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(800, 450);
            frame.setLocationRelativeTo(null);
            frame.setContentPane(new CongThucPannel());
            frame.setVisible(true);
    }
}
